import { RenderedBuildspec } from '@copperbox/millwright-state';

/**
 * Translate one rendered buildspec into a POSIX sh script for the local
 * `docker run` host (spec §14). The buildspec itself is host-neutral and
 * rendered by the shared library; this file only reproduces the CodeBuild
 * agent's PHASE semantics so the same document behaves identically:
 *
 * - install / pre_build: a failing command fails the job immediately —
 *   later phases (including post_build) never run.
 * - build: a failing command skips the rest of the build phase and flips
 *   `CODEBUILD_BUILD_SUCCEEDING` to 0, but post_build still runs (that is
 *   where the success-guarded artifact upload and cache save no-op).
 * - post_build: always runs after a completed pre_build; its own failures
 *   fail the job unless a build failure already did.
 *
 * Each command runs in its own subshell so a bare `exit` fails the command
 * without skipping the phase machinery — safe because the shared renderer
 * never assumes cross-command shell state (its own documented rule).
 *
 * Secrets are deliberately NOT read from the buildspec's env blocks here:
 * locally they arrive as plain env vars from the secrets file, injected by
 * the executor (same env-var contract, no SSM/Secrets Manager calls).
 */

const HEADER = `#!/bin/sh
# Generated by millwright run — one job's buildspec phases, CodeBuild semantics.
CODEBUILD_BUILD_SUCCEEDING=1
export CODEBUILD_BUILD_SUCCEEDING
_mw_exit=0
`;

/** Commands whose failure aborts the job on the spot (install/pre_build). */
function fatalPhase(commands: readonly string[]): string[] {
  return commands.flatMap((command) => [
    '(', command, ')', '_mw_rc=$?', 'if [ "$_mw_rc" -ne 0 ]; then exit "$_mw_rc"; fi',
  ]);
}

/** Build phase: first failure skips the rest and drops the success flag. */
function buildPhase(commands: readonly string[]): string[] {
  return commands.flatMap((command) => [
    'if [ "$_mw_exit" -eq 0 ]; then',
    '(', command, ')',
    '_mw_rc=$?',
    'if [ "$_mw_rc" -ne 0 ]; then',
    '_mw_exit=$_mw_rc',
    'CODEBUILD_BUILD_SUCCEEDING=0',
    'export CODEBUILD_BUILD_SUCCEEDING',
    'fi',
    'fi',
  ]);
}

/** post_build: runs regardless of the build result; first failure wins. */
function postBuildPhase(commands: readonly string[]): string[] {
  return commands.flatMap((command) => [
    '(', command, ')', '_mw_rc=$?',
    'if [ "$_mw_rc" -ne 0 ] && [ "$_mw_exit" -eq 0 ]; then _mw_exit=$_mw_rc; fi',
  ]);
}

export function renderLocalScript(buildspec: RenderedBuildspec): string {
  const lines: string[] = [HEADER];
  if (buildspec.phases.install) {
    lines.push('# phase: install', ...fatalPhase(buildspec.phases.install.commands));
  }
  lines.push('# phase: pre_build', ...fatalPhase(buildspec.phases.pre_build.commands));
  lines.push('# phase: build', ...buildPhase(buildspec.phases.build.commands));
  if (buildspec.phases.post_build) {
    lines.push('# phase: post_build', ...postBuildPhase(buildspec.phases.post_build.commands));
  }
  lines.push('exit "$_mw_exit"');
  return `${lines.join('\n')}\n`;
}
